### ISSUE TITLE
polymur-gateway listen port

### ISSUE THREAD

**Issue by brumer** [jamiealquiza/polymur#43]
can you add the option to bind a different port rather than 80 for the polymur-gateway?

**Comment by jamiealquiza** [comment]
Hi,

This is present in the `dev` branch. To test (from scratch - if you already have polymur installable, you should just be able to git fetch / checkout the dev branch, in place):

```
$ mkdir -p $GOPATH/src/github.com/jamiealquiza
$ git clone ghttps://github.com/jamiealquiza/polymur.git $GOPATH/src/github.com/jamiealquiza
$ go get github.com/jamiealquiza/consul
$ go install github.com/jamiealquiza/polymur/cmd/polymur-gateway
```

Options:
```
  -listen-http-port string
        Polymur-gateway listen port (http)
  -listen-https-port string
        Polymur-gateway listen port (https)
```

If unspecified, they default to 80/443. Otherwise declaring settings allows you to override with custom ports.

**Comment by jamiealquiza** [comment]
Merged into master
